### ISSUE TITLE
Unsupported Domain

### ISSUE THREAD

**Issue by preillyme** [sapcc/elektra#4]
Using a DevStack installation at `commit e08f45f77f73392b2524992d8ca6c4e628400bcc` in * branch `stable/mitaka`
```
Dashboard is not enabled for this domain.

Error ID: 0d29e012-3744-4012-9ecf-4bbf3b2a062e
Show error details 

Could not authenticate service user. Please check permissions on default for service user admin
```

![screen shot 2016-11-16 at 1 08 34 pm](https://cloud.githubusercontent.com/assets/51323/20365946/d78c9d26-abfd-11e6-9b5b-be874612566b.png)

I've verified that I can login with the `admin` credentials via:
```
curl -i \
  -H "Content-Type: application/json" \
  -d '
{ "auth": {
    "identity": {
      "methods": ["password"],
      "password": {
        "user": {
          "name": "admin",
          "domain": { "id": "default" },
          "password": "*********"
        }
      }
    }
  }
}' \
  http://localhost:5000/v3/auth/tokens ; echo
```

**Comment by tlesmann** [comment]
Have you set the configuration parameters in .env file correct? If you did (what I guess), can you please send us the log file entries related to that error.

**Comment by andypf** [comment]
@preillyme The dashboard service user has to be admin in requested domain. In this case in default. You should assign admin role on default domain for service user.

**Comment by preillyme** [comment]
Hey @tlesmann this is what I'm seeing while accessing: http://192.168.56.131:8180/Default/identity/home

```
==> /var/log/httpd/keystone.log <==
2016-11-16 07:07:18.483 2469 DEBUG keystone.middleware.auth [req-5857fe2d-0762-42a2-ac70-e698de02fcd5 - - - - -] There is either no auth token in the request or the certificate issuer is not trusted. No auth context will be set. _build_auth_context /opt/stack/keystone/keystone/middleware/auth.py:71
2016-11-16 07:07:18.492 2469 INFO keystone.common.wsgi [req-5857fe2d-0762-42a2-ac70-e698de02fcd5 - - - - -] POST http://192.168.56.132:5000/v3/auth/tokens
2016-11-16 07:07:18.513 2469 ERROR keystone.auth.controllers [req-5857fe2d-0762-42a2-ac70-e698de02fcd5 - - - - -] Could not find domain: Default
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers Traceback (most recent call last):
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers   File "/opt/stack/keystone/keystone/auth/controllers.py", line 187, in _lookup_domain
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers     domain_ref = self.resource_api.get_domain(domain_id)
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers   File "/opt/stack/keystone/keystone/common/manager.py", line 124, in wrapped
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers     __ret_val = __f(*args, **kwargs)
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers   File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 1053, in decorate
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers     should_cache_fn)
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers   File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 657, in get_or_create
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers     async_creator) as value:
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers   File "/usr/lib/python2.7/site-packages/dogpile/core/dogpile.py", line 158, in __enter__
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers     return self._enter()
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers   File "/usr/lib/python2.7/site-packages/dogpile/core/dogpile.py", line 98, in _enter
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers     generated = self._enter_create(createdtime)
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers   File "/usr/lib/python2.7/site-packages/dogpile/core/dogpile.py", line 149, in _enter_create
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers     created = self.creator()
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers   File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 625, in gen_value
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers     created_value = creator()
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers   File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 1049, in creator
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers     return fn(*arg, **kw)
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers   File "/opt/stack/keystone/keystone/resource/core.py", line 706, in get_domain
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers     raise exception.DomainNotFound(domain_id=domain_id)
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers DomainNotFound: Could not find domain: Default
2016-11-16 07:07:18.513 2469 TRACE keystone.auth.controllers
2016-11-16 07:07:18.516 2469 WARNING keystone.common.wsgi [req-5857fe2d-0762-42a2-ac70-e698de02fcd5 - - - - -] Authorization failed. The request you have made requires authentication. from 192.168.56.131

==> /var/log/httpd/keystone_access.log <==
192.168.56.131 - - [16/Nov/2016:07:07:18 +0000] "POST /v3/auth/tokens HTTP/1.1" 401 114 "-" "excon/0.51.0" 44781(us)

==> /var/log/httpd/keystone.log <==
2016-11-16 07:07:18.531 2467 DEBUG keystone.middleware.auth [req-1bac7041-b03b-4492-84a8-ecab4664dd38 - - - - -] There is either no auth token in the request or the certificate issuer is not trusted. No auth context will be set. _build_auth_context /opt/stack/keystone/keystone/middleware/auth.py:71
2016-11-16 07:07:18.539 2467 INFO keystone.common.wsgi [req-1bac7041-b03b-4492-84a8-ecab4664dd38 - - - - -] POST http://192.168.56.132:5000/v3/auth/tokens

==> /var/log/httpd/keystone_access.log <==
192.168.56.131 - - [16/Nov/2016:07:07:18 +0000] "POST /v3/auth/tokens HTTP/1.1" 201 1949 "-" "excon/0.51.0" 177482(us)

==> /var/log/httpd/keystone.log <==
2016-11-16 07:07:18.750 2470 DEBUG keystone.middleware.auth [req-b274e954-cc97-41d2-a611-76d42713fec9 92ac1418d7f0498d91c22facc875cd7d - default default -] RBAC: auth_context: {'is_delegated_auth': False, 'access_token_id': None, 'user_id': u'92ac1418d7f0498d91c22facc875cd7d', 'roles': [u'admin'], 'user_domain_id': u'default', 'trustee_id': None, 'domain_name': u'Default', 'trustor_id': None, 'token': <KeystoneToken (audit_id=0mJztLyLTyGTLCsjeDebjw, audit_chain_id=0mJztLyLTyGTLCsjeDebjw) at 0x7fe8c3632a90>, 'consumer_id': None, 'domain_id': u'default', 'trust_id': None} process_request /opt/stack/keystone/keystone/middleware/auth.py:221
2016-11-16 07:07:18.753 2470 INFO keystone.common.wsgi [req-b274e954-cc97-41d2-a611-76d42713fec9 92ac1418d7f0498d91c22facc875cd7d - default default -] GET http://192.168.56.132:5000/v3/auth/tokens
2016-11-16 07:07:18.754 2470 DEBUG keystone.common.controller [req-b274e954-cc97-41d2-a611-76d42713fec9 92ac1418d7f0498d91c22facc875cd7d - default default -] RBAC: Authorizing identity:validate_token() _build_policy_check_credentials /opt/stack/keystone/keystone/common/controller.py:80
2016-11-16 07:07:18.754 2470 DEBUG keystone.common.controller [req-b274e954-cc97-41d2-a611-76d42713fec9 92ac1418d7f0498d91c22facc875cd7d - default default -] RBAC: using auth context from the request environment _build_policy_check_credentials /opt/stack/keystone/keystone/common/controller.py:85
2016-11-16 07:07:18.756 2470 DEBUG keystone.policy.backends.rules [req-b274e954-cc97-41d2-a611-76d42713fec9 92ac1418d7f0498d91c22facc875cd7d - default default -] enforce identity:validate_token: {'is_delegated_auth': False, 'access_token_id': None, 'user_id': u'92ac1418d7f0498d91c22facc875cd7d', 'roles': [u'admin'], 'user_domain_id': u'default', 'trustee_id': None, 'domain_name': u'Default', 'trustor_id': None, 'token': <KeystoneToken (audit_id=0mJztLyLTyGTLCsjeDebjw, audit_chain_id=0mJztLyLTyGTLCsjeDebjw) at 0x7fe8c3632a90>, 'consumer_id': None, 'domain_id': u'default', 'trust_id': None} enforce /opt/stack/keystone/keystone/policy/backends/rules.py:76
2016-11-16 07:07:18.757 2470 DEBUG keystone.common.controller [req-b274e954-cc97-41d2-a611-76d42713fec9 92ac1418d7f0498d91c22facc875cd7d - default default -] RBAC: Authorization granted inner /opt/stack/keystone/keystone/common/controller.py:180

==> /var/log/httpd/keystone_access.log <==
192.168.56.131 - - [16/Nov/2016:07:07:18 +0000] "GET /v3/auth/tokens HTTP/1.1" 200 1949 "-" "fog-core/1.42.0" 57508(us)

==> /var/log/httpd/keystone.log <==
2016-11-16 07:07:18.768 2467 DEBUG keystone.middleware.auth [req-b0151ba2-0e03-43ef-aaf6-08cea2475366 - - - - -] There is either no auth token in the request or the certificate issuer is not trusted. No auth context will be set. _build_auth_context /opt/stack/keystone/keystone/middleware/auth.py:71
2016-11-16 07:07:18.769 2467 INFO keystone.common.wsgi [req-b0151ba2-0e03-43ef-aaf6-08cea2475366 - - - - -] POST http://192.168.56.132:5000/v3/auth/tokens

==> /var/log/httpd/keystone_access.log <==
192.168.56.131 - - [16/Nov/2016:07:07:18 +0000] "POST /v3/auth/tokens HTTP/1.1" 201 1984 "-" "fog-core/1.42.0" 33631(us)

==> /var/log/httpd/keystone.log <==
2016-11-16 07:07:18.810 2470 DEBUG keystone.middleware.auth [req-4e569a00-23c7-4f7b-afe6-ffe1bc0327ac 92ac1418d7f0498d91c22facc875cd7d - default default -] RBAC: auth_context: {'is_delegated_auth': False, 'access_token_id': None, 'user_id': u'92ac1418d7f0498d91c22facc875cd7d', 'roles': [u'admin'], 'user_domain_id': u'default', 'trustee_id': None, 'domain_name': u'Default', 'trustor_id': None, 'token': <KeystoneToken (audit_id=eX5APTunQ0eGRle19vpsHQ, audit_chain_id=0mJztLyLTyGTLCsjeDebjw) at 0x7fe8c3450630>, 'consumer_id': None, 'domain_id': u'default', 'trust_id': None} process_request /opt/stack/keystone/keystone/middleware/auth.py:221
2016-11-16 07:07:18.811 2470 INFO keystone.common.wsgi [req-4e569a00-23c7-4f7b-afe6-ffe1bc0327ac 92ac1418d7f0498d91c22facc875cd7d - default default -] GET http://192.168.56.132:5000/v3/users/92ac1418d7f0498d91c22facc875cd7d/projects
2016-11-16 07:07:18.812 2470 DEBUG keystone.common.controller [req-4e569a00-23c7-4f7b-afe6-ffe1bc0327ac 92ac1418d7f0498d91c22facc875cd7d - default default -] RBAC: Adding query filter params () wrapper /opt/stack/keystone/keystone/common/controller.py:220
2016-11-16 07:07:18.812 2470 DEBUG keystone.common.controller [req-4e569a00-23c7-4f7b-afe6-ffe1bc0327ac 92ac1418d7f0498d91c22facc875cd7d - default default -] RBAC: Authorizing identity:list_user_projects(user_id=92ac1418d7f0498d91c22facc875cd7d) _build_policy_check_credentials /opt/stack/keystone/keystone/common/controller.py:80
2016-11-16 07:07:18.812 2470 DEBUG keystone.common.controller [req-4e569a00-23c7-4f7b-afe6-ffe1bc0327ac 92ac1418d7f0498d91c22facc875cd7d - default default -] RBAC: using auth context from the request environment _build_policy_check_credentials /opt/stack/keystone/keystone/common/controller.py:85
2016-11-16 07:07:18.812 2470 DEBUG keystone.policy.backends.rules [req-4e569a00-23c7-4f7b-afe6-ffe1bc0327ac 92ac1418d7f0498d91c22facc875cd7d - default default -] enforce identity:list_user_projects: {'is_delegated_auth': False, 'access_token_id': None, 'user_id': u'92ac1418d7f0498d91c22facc875cd7d', 'roles': [u'admin'], 'user_domain_id': u'default', 'trustee_id': None, 'domain_name': u'Default', 'trustor_id': None, 'token': <KeystoneToken (audit_id=eX5APTunQ0eGRle19vpsHQ, audit_chain_id=0mJztLyLTyGTLCsjeDebjw) at 0x7fe8c3450630>, 'consumer_id': None, 'domain_id': u'default', 'trust_id': None} enforce /opt/stack/keystone/keystone/policy/backends/rules.py:76
2016-11-16 07:07:18.813 2470 DEBUG keystone.common.controller [req-4e569a00-23c7-4f7b-afe6-ffe1bc0327ac 92ac1418d7f0498d91c22facc875cd7d - default default -] RBAC: Authorization granted wrapper /opt/stack/keystone/keystone/common/controller.py:244

==> /var/log/httpd/keystone_access.log <==
192.168.56.131 - - [16/Nov/2016:07:07:18 +0000] "GET /v3/users/92ac1418d7f0498d91c22facc875cd7d/projects HTTP/1.1" 200 1231 "-" "fog-core/1.42.0" 95701(us)

==> /var/log/httpd/keystone.log <==
2016-11-16 07:07:18.911 2468 DEBUG keystone.middleware.auth [req-23b84423-927a-4786-abd0-5d30e35dec84 - - - - -] There is either no auth token in the request or the certificate issuer is not trusted. No auth context will be set. _build_auth_context /opt/stack/keystone/keystone/middleware/auth.py:71
2016-11-16 07:07:18.917 2468 INFO keystone.common.wsgi [req-23b84423-927a-4786-abd0-5d30e35dec84 - - - - -] POST http://192.168.56.132:5000/v3/auth/tokens

==> /var/log/httpd/keystone_access.log <==
192.168.56.131 - - [16/Nov/2016:07:07:18 +0000] "POST /v3/auth/tokens HTTP/1.1" 201 4651 "-" "fog-core/1.42.0" 125748(us)

==> /var/log/httpd/keystone.log <==
2016-11-16 07:07:19.034 2470 DEBUG keystone.middleware.auth [req-b708aafd-a833-476e-931f-64c9ce3e0db4 - - - - -] There is either no auth token in the request or the certificate issuer is not trusted. No auth context will be set. _build_auth_context /opt/stack/keystone/keystone/middleware/auth.py:71
2016-11-16 07:07:19.036 2470 INFO keystone.common.wsgi [req-b708aafd-a833-476e-931f-64c9ce3e0db4 - - - - -] POST http://192.168.56.132:5000/v3/auth/tokens

==> /var/log/httpd/keystone_access.log <==
192.168.56.131 - - [16/Nov/2016:07:07:19 +0000] "POST /v3/auth/tokens HTTP/1.1" 201 4651 "-" "fog-core/1.42.0" 43774(us)

==> /var/log/httpd/keystone.log <==
2016-11-16 07:07:19.088 2471 DEBUG keystone.middleware.auth [req-d2ff5d97-6663-4370-b671-4fbb612d0e23 - - - - -] There is either no auth token in the request or the certificate issuer is not trusted. No auth context will be set. _build_auth_context /opt/stack/keystone/keystone/middleware/auth.py:71
2016-11-16 07:07:19.095 2471 INFO keystone.common.wsgi [req-d2ff5d97-6663-4370-b671-4fbb612d0e23 - - - - -] POST http://192.168.56.132:5000/v3/auth/tokens

==> /var/log/httpd/keystone_access.log <==
192.168.56.131 - - [16/Nov/2016:07:07:19 +0000] "POST /v3/auth/tokens HTTP/1.1" 201 4651 "-" "fog-core/1.42.0" 79758(us)
```

```
07:07:15 rails.1 | Started GET "/Default" for 192.168.56.1 at 2016-11-16 07:07:15 +0000
07:07:15 rails.1 | Processing by PagesController#show as HTML
07:07:15 rails.1 |   Parameters: {"id"=>"landing", "domain_id"=>"Default"}
07:07:15 rails.1 |   Rendered pages/landing.html.haml within layouts/noscope (5.0ms)
07:07:16 rails.1 |   Rendered application/_flashes.html.haml (0.3ms)
07:07:16 rails.1 | Completed 200 OK in 730ms (Views: 720.8ms | ActiveRecord: 1.0ms)
07:07:18 rails.1 |
07:07:18 rails.1 |
07:07:18 rails.1 | Started GET "/Default/identity/home" for 192.168.56.1 at 2016-11-16 07:07:18 +0000
07:07:18 rails.1 | Processing by Identity::DomainsController#show as HTML
07:07:18 rails.1 |   Parameters: {"domain_id"=>"Default"}
07:07:18 rails.1 |   FriendlyIdEntry Load (3.0ms)  SELECT  "friendly_id_entries".* FROM "friendly_id_entries" WHERE (class_name='Domain' and (lower(key)='default' or lower(slug)='default') and endpoint='http://192.168.56.132:5000/v3/auth/tokens' )  ORDER BY "friendly_id_entries"."id" ASC LIMIT 1
07:07:18 rails.1 | [Monsoon Openstack Auth] {"error"=>{"message"=>"The request you have made requires authentication.", "code"=>401, "title"=>"Unauthorized"}}
07:07:19 rails.1 | 65a33e89-a96b-4e2f-90e4-cd71ade529a6: Unsupported Domain. Dashboard is not enabled for this domain.
07:07:19 rails.1 | ** [Raven] Could not authenticate service user. Please check permissions on Default for service user admin excluded from capture due to environment or should_capture callback
07:07:19 rails.1 |   Rendered application/errors/error.html.haml within layouts/application (2.6ms)
07:07:19 rails.1 |   Rendered application/_nav.html.haml (1.0ms)
07:07:19 rails.1 |   Rendered application/_breadcrumb.html.haml (7.6ms)
07:07:19 rails.1 |   Rendered application/_main_toolbar.html.haml (30.4ms)
07:07:19 rails.1 |   Rendered application/_help_text.html.haml (0.1ms)
07:07:19 rails.1 |   Rendered application/_flashes.html.haml (0.1ms)
07:07:19 rails.1 |   Rendered layouts/_news.html.haml (2.1ms)
07:07:19 rails.1 |   Rendered layouts/_dev_tools_script.js.erb (0.1ms)
07:07:19 rails.1 |   Rendered layouts/_dev_tools.html.haml (4.3ms)
07:07:19 rails.1 |   Rendered application/_footer.html.haml (5.3ms)
07:07:19 rails.1 | Completed 200 OK in 1453ms (Views: 750.3ms | ActiveRecord: 3.7ms)
```

development.env
```
# Devstack standard admin user/pw settings used for elektra service user
MONSOON_OPENSTACK_AUTH_API_ENDPOINT=http://192.168.56.132:5000/v3/auth/tokens
MONSOON_OPENSTACK_AUTH_API_USERID=admin
MONSOON_OPENSTACK_AUTH_API_PASSWORD=********
MONSOON_OPENSTACK_AUTH_API_DOMAIN=Default
```

**Comment by abattye** [comment]
Could you also add the results of this call via Openstack CLI

`openstack role assignment list --user admin --user-domain Default --names`

**Comment by preillyme** [comment]
@abattye: `openstack: 'role' is not an openstack command. See 'openstack --help'.`

**Comment by abattye** [comment]
Pretty sure its there, maybe you need a cli update ? I'm on  3.4.0 , but its been there for a while AFAIK.  https://github.com/openstack/python-openstackclient/commit/58f80e4c7544c0ee064c1629b3f128a628fc71d8

**Comment by preillyme** [comment]
```
openstack --version
openstack 2.3.0
```

This is the version on my DevStack VM.

**Comment by preillyme** [comment]
@abattye do you have your local.conf for DevStack that you could share?

**Comment by preillyme** [comment]
```
+---------------+---------------+-------+------------------+---------+-----------+
| Role          | User          | Group | Project          | Domain  | Inherited |
+---------------+---------------+-------+------------------+---------+-----------+
| admin         | admin@Default |       | admin@Default    |         | False     |
| service       | admin@Default |       | admin@Default    |         | False     |
| anotherrole   | admin@Default |       | admin@Default    |         | False     |
| _member_      | admin@Default |       | admin@Default    |         | False     |
| Member        | admin@Default |       | admin@Default    |         | False     |
| ResellerAdmin | admin@Default |       | admin@Default    |         | False     |
| admin         | admin@Default |       | service@Default  |         | False     |
| service       | admin@Default |       | service@Default  |         | False     |
| anotherrole   | admin@Default |       | service@Default  |         | False     |
| _member_      | admin@Default |       | service@Default  |         | False     |
| Member        | admin@Default |       | service@Default  |         | False     |
| ResellerAdmin | admin@Default |       | service@Default  |         | False     |
| admin         | admin@Default |       | demo@Default     |         | False     |
| admin         | admin@Default |       | alt_demo@Default |         | False     |
| admin         | admin@Default |       |                  | Default | False     |
+---------------+---------------+-------+------------------+---------+-----------+
```

**Comment by preillyme** [comment]
@abattye: Shouldn't this query return something?
```
SELECT  "friendly_id_entries".* FROM "friendly_id_entries" WHERE (class_name='Domain' and (lower(key)='default' or lower(slug)='default') and endpoint='http://localhost:5000/v3/auth/tokens' )  ORDER BY "friendly_id_entries"."id" ASC LIMIT 1

```

**Comment by andypf** [comment]
@preillyme: no, it shouldn't. We generate friendly ids for domains and projects and save them in dashboard database. The first time the user tries to access a "new" domain we load this domain via service user. Because we don't know what kind of information the user provides in the url name or id we try both to load domain by id and if it fails then by name. That's why you see Errors in log like "DomainNotFound: Could not find domain: Default". Friendly IDs are not the cause for Unsupported Domain!

**Comment by andypf** [comment]
@preillyme: you can add EXCON_DEBUG = true to your .env (and restart elektra). This should show what Excon is sending to the API and what is responsed.

**Comment by preillyme** [comment]
@andypf: I'm trying that now.

**Comment by andypf** [comment]
@preillyme: ok, can you add the log output?

**Comment by preillyme** [comment]
@andypf:
```
$ foreman start -e development.env
12:16:30 rails.1 | started with pid 3508
12:16:35 rails.1 | => Booting Puma
12:16:35 rails.1 | => Rails 4.2.4 application starting in development on http://0.0.0.0:8180
12:16:35 rails.1 | => Run `rails server -h` for more startup options
12:16:35 rails.1 | => Ctrl-C to shutdown server
12:16:35 rails.1 | => Trusted IP 192.168.56.1
12:16:35 rails.1 | => Auth Endpoint http://192.168.56.133:5000/v3/auth/tokens
12:16:35 rails.1 |
12:16:35 rails.1 | ################ WARNING ################
12:16:35 rails.1 | Automation ENV variables not set
12:16:35 rails.1 | Env variable 'ARC_UPDATES_URL' not set.
12:16:35 rails.1 | Env variable 'ARC_PKI_URL' not set.
12:16:35 rails.1 | Env variable 'ARC_BROKER_URL' not set.
12:16:35 rails.1 | #########################################
12:16:35 rails.1 |
12:16:35 rails.1 | I, [2016-11-16T12:16:35.341915 #3508]  INFO -- sentry: ** [Raven] Raven 1.2.3 configured not to capture errors.
12:16:35 rails.1 | D, [2016-11-16T12:16:35.659887 #3508] DEBUG -- : Mount plugin automation as automation_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.660917 #3508] DEBUG -- : Mount plugin bare-metal-hana as bare_metal_hana_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.661512 #3508] DEBUG -- : Mount plugin block-storage as block_storage_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.662059 #3508] DEBUG -- : Mount plugin compute as compute_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.662585 #3508] DEBUG -- : Mount plugin dns-service as dns_service_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.663081 #3508] DEBUG -- : Mount plugin identity as identity_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.663718 #3508] DEBUG -- : Mount plugin image as image_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.664199 #3508] DEBUG -- : Mount plugin request as inquiry_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.665152 #3508] DEBUG -- : Mount plugin key-manager as key_manager_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.665719 #3508] DEBUG -- : Mount plugin loadbalancing as loadbalancing_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.666315 #3508] DEBUG -- : Mount plugin monitoring as monitoring_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.666830 #3508] DEBUG -- : Mount plugin networking as networking_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.667304 #3508] DEBUG -- : Mount plugin object-storage as object_storage_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.668015 #3508] DEBUG -- : Mount plugin resource-management as resource_management_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.668573 #3508] DEBUG -- : Mount plugin shared-filesystem-storage as shared_filesystem_storage_plugin
12:16:35 rails.1 | D, [2016-11-16T12:16:35.669185 #3508] DEBUG -- : Mount plugin webconsole as webconsole_plugin
12:16:36 rails.1 | Puma 2.16.0 starting...
12:16:36 rails.1 | * Min threads: 0, max threads: 16
12:16:36 rails.1 | * Environment: development
12:16:36 rails.1 | * Listening on tcp://0.0.0.0:8180
12:16:43 rails.1 |
12:16:43 rails.1 |
12:16:43 rails.1 | Started GET "/default" for 192.168.56.1 at 2016-11-16 12:16:43 +0000
12:16:43 rails.1 |   ActiveRecord::SchemaMigration Load (0.3ms)  SELECT "schema_migrations".* FROM "schema_migrations"
12:16:43 rails.1 | Processing by PagesController#show as HTML
12:16:43 rails.1 |   Parameters: {"id"=>"landing", "domain_id"=>"default"}
12:16:43 rails.1 |   Rendered pages/landing.html.haml within layouts/noscope (16.9ms)
12:16:44 rails.1 |   ActiveRecord::SessionStore::Session Load (0.5ms)  SELECT  "sessions".* FROM "sessions" WHERE "sessions"."session_id" = $1  ORDER BY "sessions"."id" ASC LIMIT 1  [["session_id", "eedb310e4652805e6e3340315c6cadf9"]]
12:16:44 rails.1 |   Rendered application/_flashes.html.haml (1.9ms)
12:16:44 rails.1 | Completed 200 OK in 1046ms (Views: 1039.4ms | ActiveRecord: 3.6ms)
12:16:44 rails.1 |    (0.2ms)  BEGIN
12:16:44 rails.1 |    (0.4ms)  COMMIT
12:16:46 rails.1 |
12:16:46 rails.1 |
12:16:46 rails.1 | Started GET "/default/identity/home" for 192.168.56.1 at 2016-11-16 12:16:46 +0000
12:16:46 rails.1 | Processing by Identity::DomainsController#show as HTML
12:16:46 rails.1 |   Parameters: {"domain_id"=>"default"}
12:16:46 rails.1 |   FriendlyIdEntry Load (0.9ms)  SELECT  "friendly_id_entries".* FROM "friendly_id_entries" WHERE (class_name='Domain' and (lower(key)='default' or lower(slug)='default') and endpoint='http://192.168.56.133:5000/v3/auth/tokens' )  ORDER BY "friendly_id_entries"."id" ASC LIMIT 1
12:16:47 rails.1 | 1b5af8c9-a401-4040-b3fb-ec3018e3b7fb: Unsupported Domain. Dashboard is not enabled for this domain.
12:16:47 rails.1 | ** [Raven] Could not authenticate service user. Please check permissions on default for service user admin excluded from capture due to environment or should_capture callback
12:16:47 rails.1 |   ActiveRecord::SessionStore::Session Load (1.1ms)  SELECT  "sessions".* FROM "sessions" WHERE "sessions"."session_id" = $1  ORDER BY "sessions"."id" ASC LIMIT 1  [["session_id", "eedb310e4652805e6e3340315c6cadf9"]]
12:16:47 rails.1 |   Rendered application/errors/error.html.haml within layouts/application (8.3ms)
12:16:48 rails.1 |   Rendered application/_nav.html.haml (5.4ms)
12:16:48 rails.1 |   Rendered application/_breadcrumb.html.haml (8.6ms)
12:16:48 rails.1 | /home/vagrant/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/fog-core-1.42.0/lib/fog/core/attributes/default.rb:52: warning: redefining `object_id' may cause serious problems
12:16:48 rails.1 |   Rendered application/_main_toolbar.html.haml (307.7ms)
12:16:48 rails.1 |   Rendered application/_help_text.html.haml (2.2ms)
12:16:48 rails.1 |   Rendered application/_flashes.html.haml (0.1ms)
12:16:48 rails.1 |   Rendered layouts/_news.html.haml (24.0ms)
12:16:48 rails.1 |   Rendered layouts/_dev_tools_script.js.erb (0.8ms)
12:16:48 rails.1 |   Rendered layouts/_dev_tools.html.haml (31.2ms)
12:16:48 rails.1 |   Rendered application/_footer.html.haml (35.6ms)
12:16:48 rails.1 | Completed 200 OK in 1664ms (Views: 1150.5ms | ActiveRecord: 4.5ms)
12:16:48 rails.1 |    (1.0ms)  BEGIN
12:16:48 rails.1 |    (1.0ms)  COMMIT
```

**Comment by andypf** [comment]
@preillyme: did you add EXCON_DEBUG=true to ENV? There should be something like excon.request in the output

**Comment by preillyme** [comment]
@andypf: fixed paste above.

**Comment by andypf** [comment]
@preillyme: one more try, could you please add  RegionOne here: https://github.com/sapcc/elektra/blob/master/config/application.rb#L90

Should look like: config.default_region = ENV['MONSOON_DASHBOARD_REGION'] || ['RegionOne','eu-de-1','staging','europe']

**Comment by preillyme** [comment]
@andypf: appears to have same issue. Are you available on IRC or anything like that?

**Comment by andypf** [comment]
@preillyme: No, unfortunately not.  I'm pretty sure the region is responsible for this problem

**Comment by preillyme** [comment]
@andypf: Can you share your local.conf for DevStack?

**Comment by abattye** [comment]
For reference the issue was caused because the 'default' devstack install was using Keystone V2 which has no domain support - adding `IDENTITY_API_VERSION=3` to local.conf enables V3 support

**Comment by tlesmann** [comment]
We'll add this to the readme. 
@preillyme Thanks for the help and being the guinea pig :)
